name: community
description: A new Flutter project.

flutter: 
  uses-material-design: true

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  html: ^0.15.4
  image_picker: ^1.0.5
  webview_flutter: ^4.4.2
  webview_flutter_android: 3.12.1
  webview_flutter_wkwebview: ^3.9.4
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.0
  cloud_firestore: 4.13.5
  cloud_firestore_platform_interface: ^6.0.10
  cloud_firestore_web: ^3.8.10
  firebase_auth: 4.15.3
  firebase_auth_platform_interface: ^7.0.9
  firebase_auth_web: ^5.8.12
  firebase_core: ^2.13.1
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: ^2.10.0
  firebase_storage: 11.5.6
  firebase_performance: 0.9.3+8
  firebase_performance_platform_interface: 0.1.4+16
  firebase_performance_web: 0.1.4+16
  flutter_animate: ^4.3.0
  flutter_cache_manager: ^3.3.1
  flutter_native_splash: ^2.3.7
  font_awesome_flutter: ^10.6.0
  from_css_color: 2.0.0
  go_router: ^12.1.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.0.2
  google_sign_in_android: ^6.1.20
  google_sign_in_ios: ^5.6.5
  google_sign_in_platform_interface: ^2.4.3
  google_sign_in_web: ^0.12.2+1
  intl: 0.18.1
  json_path: ^0.6.3
  page_transition: ^2.1.0
  path_provider: ^2.1.1
  path_provider_android: ^2.2.1
  path_provider_foundation: ^2.3.1
  path_provider_platform_interface: ^2.1.1
  plugin_platform_interface: ^2.1.7
  provider: ^6.1.1
  rxdart: 0.27.7
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: ^2.3.1
  shared_preferences_web: ^2.2.1
  sign_in_with_apple: ^5.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  statistics: ^1.0.26
  sqflite: ^2.3.0
  stream_transform: 2.1.0
  timeago: ^3.6.0
  universal_io: 2.2.2
  url_launcher: ^6.2.2
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.1
  url_launcher_platform_interface: ^2.2.0
  xml: 6.3.0
  youtube_player_iframe: 4.0.4
  firebase_database: ^10.2.2
  logger: 2.0.2+1

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: ^3.0.1
  image: 4.1.3
  lints: 3.0.0

  flutter_test:
    sdk: flutter


  