// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcSx6qLCPGxWldh7ZomPqSZ-Vy8dUvet8',
    appId: '1:925684634960:web:13d48e31c3d7949f984855',
    messagingSenderId: '925684634960',
    projectId: 'dtproject-3930e',
    authDomain: 'dtproject-3930e.firebaseapp.com',
    databaseURL: 'https://dtproject-3930e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtproject-3930e.appspot.com',
    measurementId: 'G-7LEWN1QDPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMkz4evTy9or1ajGUqWMnL36nJcB3huIo',
    appId: '1:925684634960:android:f8d82ac1dd236850984855',
    messagingSenderId: '925684634960',
    projectId: 'dtproject-3930e',
    databaseURL: 'https://dtproject-3930e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtproject-3930e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Of9R1NgGrixgCEA69kRaBF1rXL7ISAU',
    appId: '1:925684634960:ios:7971d6474ed2c38c984855',
    messagingSenderId: '925684634960',
    projectId: 'dtproject-3930e',
    databaseURL: 'https://dtproject-3930e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtproject-3930e.appspot.com',
    iosBundleId: 'com.example.maplemoa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Of9R1NgGrixgCEA69kRaBF1rXL7ISAU',
    appId: '1:925684634960:ios:baef2d99e2f10747984855',
    messagingSenderId: '925684634960',
    projectId: 'dtproject-3930e',
    databaseURL: 'https://dtproject-3930e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dtproject-3930e.appspot.com',
    iosBundleId: 'com.example.maplemoa.RunnerTests',
  );
}
